### PR TITLE
fix #49 - restructure table response

### LINKED ISSUE #49: Fix table response structure
**Current behaviour**:
A new message is send for every table row.
**Expected behaviour**:
Compose the whole message using markdown and newlines and send a single slack message.
**Would you like to work on it?**
Yes

### PR DESCRIPTION
**Pull request by hkedia321**
Changes:
- reformat table response data
- send all the table rows in a single message instead of new message for line

screenshot:
image

### CODE REVIEW

**Comment by anshumanv** [comment]
Just see why codacy is failing.

**Comment by AliAyub007** [comment]
@hkedia321 Check fix codacy errors.

**Comment by hkedia321** [comment]
@AliAyub007 fixed the codacy error.

**Comment by hkedia321** [comment]
@AliAyub007 Please review.

**Pull request merged**
